### PR TITLE
feat: resizeable window

### PR DESCRIPTION
**Pull request by sekwah41**

### CODE REVIEW

**Comment by sekwah41** [comment]
Hopefully fixes #261 and once a release is generated should address #243

**Comment by sekwah41** [comment]
Sorry for the pre-commit fixes too at the same time it was complaining. Just focus on the css changes and try running it locally.

**Comment by roldanjr** [comment]
I already tested it out, but I saw some issues along the way so I decided to add the fixes here. I also updated the prettier configuration but currently have no idea how to resolve the pre-commit consistency check action errors.

**Comment by sekwah41** [comment]
I will take a look after work @roldanjr. There are also a few visual issues I've found that need slight tweaks to.

**Comment by sekwah41** [comment]
I may make the pre-commit one less strict, its just a nice one for some of the basic stuff to clean things up and enforce certain rules as it can hook into stuff like prettier. 

But the way you can run it is `pre-release run` and it'll run over your files with changes.

Or run `pre-release run --all-files` to go over all files.

**Comment by sekwah41** [comment]
image
need to also check this out to find whats going on there.

Seems originally the window was too thin to notice the visual bug but when it goes smaller than a certain amount suddenly it snaps to look like this.

**Comment by sekwah41** [comment]
I also need to fix up the settings window to allow that to scale vertically properly.

A lot of these changes we are making for resizing should also assist with mobile support due to varying screen sizes :D

**Comment by sekwah41** [comment]
I will need to look tomorrow. The trains have been cancelled and screwed up so my plans are completely screwed up.

**Comment by sekwah41** [comment]
Ive also solved #311 to allow us to tinker with the UI easier.

**Review by roldanjr — APPROVED** [review]
LGTM! Do you still have something working on this PR @sekwah41?

**Comment by sekwah41** [comment]
Just a few small tweaks. I believe the last one is modifying this to be css based shortening.
image
Though I am doing that now.

**Comment by sekwah41** [comment]
Finished the final part I wanted @roldanjr. The issue I had was i was trying to mess with the layout a lot and then forgot the timer was a display: grid; type and that was what was making the size not act as I was expecting.

I've updated it to use flexboxes instead so it resizes a little more cleanly especially with the css ellipsis hiding.

**Comment by sekwah41** [comment]
image
image
image

**Comment by sekwah41** [comment]
As long as the compact mode isn't broken this pr is ready to merge. I'll check it tomorrow as it's past midnight right now.

**Comment by roldanjr** [comment]
The compact mode layout has been broken. Already pushed the fix for that.
I also add restrictions to users from resizing the window during the compact mode.

You can merge this @sekwah41 after you check my updates.

**Comment by sekwah41** [comment]
image
the minimum size the  main app can go to is too small now

**Comment by sekwah41** [comment]
Found the issue. It's a side effect of making the window resizeable after setting the minimum size.

**Comment by sekwah41** [comment]
The only thing I may say is due to how it was working before. The compact mode may still have some issues on certain operating systems when the fullscreen break is used. Though we can investigate that when the reports come in and on which os.

Though ill try to do a quick test on windows and mac once they have built.

**Comment by sekwah41** [comment]
image
I just got this error coming out of full screen break.

**Comment by sekwah41** [comment]
imagewindows after a full iteration and going back to compact mode

**Comment by sekwah41** [comment]
Was just playing a game of league and realised we are not cancelling the global listener to the escape key.

**Comment by sekwah41** [comment]
Confirmed works on mac and Linux. Though windows doesn't properly resize fully. Will try listening to the fullscreen event later.

**Comment by gillisandrew** [comment]
Why are there so many whitespace changes?

**Comment by gillisandrew** [comment]
Oh I see, prettier config was updated. Any chance we can keep that in a separate pull request?

**Comment by sekwah41** [comment]
Thats my bad partially i told precommit to run over all the files to clean it up.

image

You can ignore the whitespace in the github ui.

**Comment by sekwah41** [comment]
Whitespaces should be sorted @gillisandrew and will be a different pr.

**Comment by sekwah41** [comment]
I've done testing on mac, windows and Linux with the resizing issues and it seems to be fully sorted now. Had to fix a series of annoying behaviours and mostly windows was the problem.

**Review by gillisandrew — APPROVED** [review]

**Comment by sekwah41** [comment]
@gillisandrew agreed though we can try to enforce it after this release more

**Pull request merged**
