### PR TITLE
Added nvmrc for node version

### PR DESCRIPTION
**Pull request by bonniesimon**
Description:
- When I tried to set up the project locally, I got the error "ERR_OSSL_EVP_UNSUPPORTED". This was because I was using the wrong version of node. Thus I had a do a little guessing game to figure out the correct node version for the project. 
- Adding a nvmrc will allow anyone to instantly know which node version the project uses along with the added benefit for nvm users who can simply use `nvm use` to set the correct node version.

PS: Also when I ran `yarn dev:app`, I got the error 

> "Cannot find module '@pomatez/shareables' or its corresponding type declarations.  TS2307"

I navigated into the `app/shareables` folder & ran yarn to fix this. Let me know if I should add this to the documentation or if this came up simply because I missed something while setting up.

### CODE REVIEW

**Comment by roldanjr** [comment]
Hi @bonniesimon, thanks for the effort, man. I am revamping this project, and the `.nvmrc` is already included under the root directory so people will not encounter the same problem you have experienced.

You can check the [revamp](https://github.com/roldanjr/pomatez/tree/revamp) branch for your reference :)

**Comment by bonniesimon** [comment]
Can we merge this to master so that no one gets confused till the revamp is merged? It's totally cool if you don't want to.
Also what about the app/shareables error. Should we do a yarn install in the app/shareables folder in order to set the project up? If yes, I could add this to the documentation.

**Comment by roldanjr** [comment]
Sorry @bonniesimon but I can't merge it to the master branch. Soon, feel free to contribute after the revamp is done.
Thanks for your willingness to help. I'll close this PR for now.

**Comment by bonniesimon** [comment]
@roldanjr I just realized that the revamp is going to be in React! I would love to contribute since I know React. Is there a board or place where I can pick up issues related to the revamp. Thank you.

**Comment by AlastairVisku** [comment]
The current main branch is react anyway.

**Comment by sekwah41** [comment]
The current branch is react anyway @bonniesimon. Though feel free to pick up any issues off the issues raised. I need to look at the project board and organise the priority tbh or some vague level of priority.

**Pull request closed without merging**
