### PR TITLE
Fixed icons for linux direct install

### PR DESCRIPTION
**Pull request by sekwah41**
image

Testing on fedora it fixes the issue. Id just verify that it doesn't mess up any of the other parts using snap or anything

### CODE REVIEW

**Comment by sekwah41** [comment]
With testing it fixes this issue #106.

If you install it using the gui, it doesn't show up but after installing it shows up in the menu which is what matters.
image

**Comment by roldanjr** [comment]
Thank you @sekwah41  for the effort. But I did not see any difference.

You just renamed the icon file and changed the category for linux packages. 

Did you try to build it first and test if it's working before modifying the code?

**Comment by sekwah41** [comment]
That's actually all there is to it. I changed the Linux icon to point at the folder and then it looks for a icon file. It also looks for specific ones such as icon256x256.png.

The issue was the rpm was outputting it to a folder called 0x0 which isn't a valid size. Now it outputs two. One in the 256x256 and another in 64x64 or something like that (I forget the other one)

https://www.electron.build/icons#linux

Try building them before and after and use something like 7zip to explore the packages.

I can reinstall it to double check if you arn't seeing them pop up in the 256x256 folder like I mentioned.

**Comment by sekwah41** [comment]
Though I'll have to test removing the 256x256 and see if the auto resizer fully kicks in

**Comment by roldanjr** [comment]
Yes, I really appreciate what you did. 

Before these issues came up. The original code is like this;
```json
"icon": "./src/assets/logo-dark.png"
```

I realized that this does not pointing to the correct build folder included in the packaging. 

So I changed it like this

image

As we can see `build` folder contains all the assets for production build.

image

image


That's why I ask if you tried to build the code from the master's branch and test it if it works because I already modified it and the only thing that lacking is testing it to a real `fedora os`.

**Comment by sekwah41** [comment]
Ohhhhhhhhhh yea I tested it before. You need the name specifically to be icon not logo. It's weird but that's what fixed it. It's the actual name that's the problem. Also I pointed it to the folder as it auto detects the files named icon or if you add the Mac icons file. The current master branch does the 0x0 behaviour I mentioned before.

**Comment by roldanjr** [comment]
I understand. If that's the only way to fix it.

But we don't actually need to change the `logo-dark@2x.png` because it is intended for MacOS.

What we can do to not mess around with other files is renaming the `logo-dark.png` to `logo-dark256x256.png` .

And making it sure that it only affects the `rpm` package. 

image

Please let me know your thought too about this.

**Comment by sekwah41** [comment]
Checking and yea its all fine now on fedora with the new edits.

**Comment by sekwah41** [comment]
Just to clarify I reverted the changes and made the specific edits you'd said :) that all works fine.

**Comment by roldanjr** [comment]
Thank you @sekwah41 . Sorry for the late action.

**Pull request merged**
