### PR TITLE
feature: added compact mode

### PR DESCRIPTION
**Pull request by WeslleyNasRocha**
# What has been added

I've added a new mode, that makes the window smaller and joins well with "always on top".
Peek 03-09-2021 09-48

### CODE REVIEW

**Comment by edwatt** [comment]
This was exactly the feature that I was looking for. Your changes are working for me on Windows 11 x64. Thanks!

**Comment by AugustasV** [comment]
image
On Linux I see exclamation mark in that place where it's possible to make it compact.

**Review by roldanjr — APPROVED** [review]
LGTM!

**Comment by sekwah41** [comment]
I'll run through some tests on it later on windows and Manjaro.

**Comment by WeslleyNasRocha** [comment]
I have developed it on a linux distro, but i moved into a macbook and i runs fine on macs, but can't test again on linux

**Comment by AugustasV** [comment]
So right now we have to deploy this version, so everyone could have this feature?

**Pull request merged**
