### PR TITLE
chore(ci): upload artifacts

### PR DESCRIPTION
**Pull request by sekwah41**
Helps with being able to test in vm's and such without having to compile locally for each.

### CODE REVIEW

**Comment by roldanjr** [comment]
Woah! This is so nice 👏🏼

**Comment by sekwah41** [comment]
Will need to run it later, windows seems to be complaining about running `yarn install`

**Review by WeslleyNasRocha — APPROVED** [review]

**Review by roldanjr — APPROVED** [review]
LGTM!

**Comment by sekwah41** [comment]
They passed as I did a typo which bugged the pipelines.

Ill merge once I'm happy its uploading as expected and show you guys the outputs.

**Pull request merged**
